# Generated by Django 4.2.13 on 2024-06-11 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, verbose_name='Token')),
                ('isActive', models.BooleanField(default=False, verbose_name='Token ishlaydimi?')),
                ('createdTime', models.DateTimeField(auto_now_add=True, verbose_name='Token olingan vaqt')),
                ('updatedTime', models.DateTimeField(auto_now=True, verbose_name='Token eskirgan vaqt')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokenlar',
                'db_table': 'tokens',
                'ordering': ['-createdTime'],
            },
        ),
    ]
