# Generated by Django 4.2.13 on 2024-06-05 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_applicant_options_alter_contractprice_options_and_more'),
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examresult',
            options={'verbose_name': 'Imtihon natijasi', 'verbose_name_plural': 'Imtihon natijalari'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Savol', 'verbose_name_plural': 'Test savollari'},
        ),
        migrations.AlterModelOptions(
            name='test',
            options={'verbose_name': 'Test', 'verbose_name_plural': 'Testlar'},
        ),
        migrations.AlterField(
            model_name='examresult',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_result', to='users.applicant', verbose_name='Arizachi'),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='result',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Natijasi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Savol rasmi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.TextField(verbose_name='Savol matni'),
        ),
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='test_app.test', verbose_name='Savol testi'),
        ),
        migrations.AlterField(
            model_name='question',
            name='trueResponse',
            field=models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=1, verbose_name="To'g'ri javob"),
        ),
        migrations.AlterField(
            model_name='test',
            name='createdTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Test ochilgan sana'),
        ),
        migrations.AlterField(
            model_name='test',
            name='isActive',
            field=models.BooleanField(default=False, verbose_name='Test aktivmi?'),
        ),
        migrations.AlterField(
            model_name='test',
            name='language',
            field=models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian')], max_length=2, verbose_name='Test tili'),
        ),
        migrations.AlterField(
            model_name='test',
            name='questionsCount',
            field=models.IntegerField(verbose_name="Arizachiga fan bo'yicha ko'rinuvchi savollar soni"),
        ),
        migrations.AlterField(
            model_name='test',
            name='science',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='users.science', verbose_name='Test fani'),
        ),
    ]
