# Generated by Django 4.2.13 on 2024-06-25 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0003_examresult_trueresponsecount_alter_examresult_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Savolning aktivligi'),
        ),
    ]
