# Generated by Django 4.2.13 on 2024-06-25 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0004_question_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name="Test o'chirilganmi?"),
        ),
    ]
