# Generated by Django 4.2.13 on 2024-06-27 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0005_test_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='createdTime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Natijaga ochilgan sana'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examresult',
            name='intervalTime',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Interval (daqiqa)'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='totalScore',
            field=models.PositiveIntegerField(default=0, verbose_name='Umumiy ball'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examresult',
            name='userResponses',
            field=models.JSONField(blank=True, null=True, verbose_name='Foydalanuvchi javoblari'),
        ),
    ]
