# Generated by Django 4.2.13 on 2024-06-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0006_examresult_createdtime_examresult_intervaltime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examresult',
            name='totalScore',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Umumiy ball'),
        ),
    ]
