# Generated by Django 4.2.13 on 2024-05-08 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_applicant_directionofeducation_and_more'),
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='tests.test'),
        ),
        migrations.AlterField(
            model_name='test',
            name='directionOfEducation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='users.educationalareas'),
        ),
        migrations.AlterField(
            model_name='test',
            name='science',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tests', to='tests.science'),
        ),
    ]
