# Generated by Django 4.2.13 on 2024-05-08 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_alter_question_test_alter_test_directionofeducation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
