# Generated by Django 4.2.13 on 2024-05-13 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='language',
            field=models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian')], max_length=2),
        ),
    ]
