# Generated by Django 4.2.13 on 2024-05-08 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('tgId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('phoneNumber', models.CharField(max_length=20, unique=True)),
                ('pinfl', models.CharField(max_length=14, unique=True)),
                ('firstName', models.CharField(max_length=255, null=True)),
                ('lastName', models.CharField(max_length=255, null=True)),
                ('middleName', models.CharField(max_length=255, null=True)),
                ('passport', models.CharField(max_length=20, null=True, unique=True)),
                ('contractFile', models.CharField(max_length=255, null=True)),
                ('olympian', models.BooleanField(default=False)),
                ('createdTime', models.DateTimeField(auto_now_add=True)),
                ('updatedTime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'applicants',
            },
        ),
        migrations.CreateModel(
            name='EducationalAreas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameUz', models.CharField(max_length=255)),
                ('nameRu', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'educational_areas',
            },
        ),
        migrations.CreateModel(
            name='SimpleUser',
            fields=[
                ('tgId', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255, null=True)),
                ('language', models.CharField(choices=[('uz', 'uz'), ('ru', 'ru')], max_length=2)),
            ],
            options={
                'db_table': 'simple_users',
            },
        ),
        migrations.CreateModel(
            name='TypeOfEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameUz', models.CharField(max_length=255)),
                ('nameRu', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'types_of_education',
            },
        ),
        migrations.CreateModel(
            name='Olympian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vaucher', models.BigIntegerField(default=0)),
                ('certificateImage', models.CharField(max_length=255, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olympian_user', to='users.applicant')),
            ],
            options={
                'db_table': 'olympians',
            },
        ),
        migrations.CreateModel(
            name='ContractPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('directionOfEducation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_price', to='users.educationalareas')),
                ('typeOfEducation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_price', to='users.typeofeducation')),
            ],
            options={
                'db_table': 'contract_prices',
            },
        ),
        migrations.AddField(
            model_name='applicant',
            name='directionOfEducation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants', to='users.educationalareas'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='typeOfEducation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants', to='users.typeofeducation'),
        ),
    ]
