# Generated by Django 4.2.13 on 2024-05-08 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='directionOfEducation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants', to='users.educationalareas'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='typeOfEducation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants', to='users.typeofeducation'),
        ),
        migrations.AlterField(
            model_name='contractprice',
            name='directionOfEducation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_price', to='users.educationalareas'),
        ),
        migrations.AlterField(
            model_name='contractprice',
            name='typeOfEducation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_price', to='users.typeofeducation'),
        ),
    ]
