# Generated by Django 4.2.13 on 2024-05-31 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DirectionOdEducation',
            new_name='DirectionOfEducation',
        ),
    ]
