# Generated by Django 4.2.13 on 2024-06-05 06:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_directionodeducation_directionofeducation'),
    ]

    operations = [
        migrations.AddField(
            model_name='directionofeducation',
            name='examPassPercentage',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
