# Generated by Django 4.2.13 on 2024-06-05 06:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_directionofeducation_exampasspercentage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicant',
            options={'ordering': ['-createdTime'], 'verbose_name': 'Arizachi', 'verbose_name_plural': 'Arizachilar'},
        ),
        migrations.AlterModelOptions(
            name='contractprice',
            options={'verbose_name': 'Kontrakt miqdori', 'verbose_name_plural': 'Kontrakt miqdorlari'},
        ),
        migrations.AlterModelOptions(
            name='directionofeducation',
            options={'verbose_name': 'Fakultet', 'verbose_name_plural': 'Fakultetlar'},
        ),
        migrations.AlterModelOptions(
            name='olympian',
            options={'verbose_name': 'Olimpiadachi', 'verbose_name_plural': 'Olimpiadachilar'},
        ),
        migrations.AlterModelOptions(
            name='science',
            options={'verbose_name': 'Fan', 'verbose_name_plural': 'Fanlar'},
        ),
        migrations.AlterModelOptions(
            name='simpleuser',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.AlterModelOptions(
            name='typeofeducation',
            options={'verbose_name': "Ta'lim turi", 'verbose_name_plural': "Ta'lim turlari"},
        ),
        migrations.AlterField(
            model_name='applicant',
            name='additionalPhoneNumber',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name="Qo'shimcha telefon raqami"),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='applicationStatus',
            field=models.CharField(choices=[('DRAFT', 'QORALAMA'), ('SUBMITTED', 'ARIZA YUBORILDI'), ('REJECTED', 'ARIZA RAD ETILDI'), ('ACCEPTED', 'ARIZA QABUL QILINDI'), ('PASSED', "IMTHONDAN MUVAFFAQIYATLI O'TDI"), ('FAILED', 'IMTIHON MUVAFFAQIYATSIZ'), ('EXAMINED', 'TEKSHIRILDI')], default='DRAFT', max_length=20, verbose_name='Arizachi holati'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='contractFile',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Kontrakt shartnomasi'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='createdTime',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ariza yuborilgan sana'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='directionOfEducation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants', to='users.directionofeducation', verbose_name='Fakultet'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='firstName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ismi'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='languageOfEducation',
            field=models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian')], default='uz', max_length=2, verbose_name="Ta'lim tili"),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='lastName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Familiyasi'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='middleName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Sha'rifi"),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='olympian',
            field=models.BooleanField(default=False, verbose_name='Olimpiadachimi?'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='passport',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Pasport seriya'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phoneNumber',
            field=models.CharField(max_length=20, unique=True, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='pinfl',
            field=models.CharField(max_length=14, unique=True, verbose_name='Pinfl'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='tgId',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Telegram id'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='typeOfEducation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants', to='users.typeofeducation', verbose_name="Ta'lim turi"),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='updatedTime',
            field=models.DateTimeField(auto_now=True, verbose_name="oxirgi o'zgarish sanasi"),
        ),
        migrations.AlterField(
            model_name='contractprice',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Kontrakt miqdori'),
        ),
        migrations.AlterField(
            model_name='contractprice',
            name='directionOfEducation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_price', to='users.directionofeducation', verbose_name='Fakultet'),
        ),
        migrations.AlterField(
            model_name='contractprice',
            name='typeOfEducation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contract_price', to='users.typeofeducation', verbose_name="Ta'lim turi"),
        ),
        migrations.AlterField(
            model_name='directionofeducation',
            name='examPassPercentage',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name="Imtihondan o'tish foizi"),
        ),
        migrations.AlterField(
            model_name='directionofeducation',
            name='nameRu',
            field=models.CharField(max_length=255, verbose_name='Fakultet nomi ru'),
        ),
        migrations.AlterField(
            model_name='directionofeducation',
            name='nameUz',
            field=models.CharField(max_length=255, verbose_name='Fakultet nomi uz'),
        ),
        migrations.AlterField(
            model_name='directionofeducation',
            name='sciences',
            field=models.ManyToManyField(blank=True, to='users.science', verbose_name='Imtihon fanlari'),
        ),
        migrations.AlterField(
            model_name='olympian',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='olympian_user', to='users.applicant', verbose_name='Arizachi'),
        ),
        migrations.AlterField(
            model_name='olympian',
            name='certificateImage',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sertifikati'),
        ),
        migrations.AlterField(
            model_name='olympian',
            name='result',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Imtihon natijasi'),
        ),
        migrations.AlterField(
            model_name='olympian',
            name='vaucher',
            field=models.BigIntegerField(default=0, verbose_name='Vaucheri'),
        ),
        migrations.AlterField(
            model_name='science',
            name='nameRu',
            field=models.CharField(max_length=255, verbose_name='Fan nomi ru'),
        ),
        migrations.AlterField(
            model_name='science',
            name='nameUz',
            field=models.CharField(max_length=255, verbose_name='Fan nomi uz'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='fullname',
            field=models.CharField(max_length=255, null=True, verbose_name='Ism-familiya'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='language',
            field=models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian')], max_length=2, verbose_name='Til'),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='tgId',
            field=models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Telegram id'),
        ),
        migrations.AlterField(
            model_name='typeofeducation',
            name='nameRu',
            field=models.CharField(max_length=255, verbose_name="Ta'lim turi nomi ru"),
        ),
        migrations.AlterField(
            model_name='typeofeducation',
            name='nameUz',
            field=models.CharField(max_length=255, verbose_name="Ta'lim turi nomi uz"),
        ),
    ]
