# Generated by Django 4.2.13 on 2024-05-10 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_question_image'),
        ('users', '0003_alter_applicant_contractfile_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EducationalAreas',
            new_name='DirectionOdEducation',
        ),
    ]
