# Generated by Django 4.2.13 on 2024-05-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_educationalareas_directionodeducation'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='languageOfEducation',
            field=models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian')], default='uz', max_length=2),
        ),
        migrations.AlterField(
            model_name='simpleuser',
            name='language',
            field=models.CharField(choices=[('uz', 'Uzbek'), ('ru', 'Russian')], max_length=2),
        ),
    ]
