# Generated by Django 4.2.13 on 2024-06-10 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_applicant_options_alter_contractprice_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directionofeducation',
            name='nameRu',
            field=models.CharField(max_length=255, verbose_name="Ta'lim yo'nalishi ru"),
        ),
        migrations.AlterField(
            model_name='directionofeducation',
            name='nameUz',
            field=models.CharField(max_length=255, verbose_name="Ta'lim yo'nalishi nomi uz"),
        ),
    ]
