# Generated by Django 4.2.13 on 2024-06-10 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_directionofeducation_nameru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='directionofeducation',
            options={'verbose_name': "Ta'lim yo'nalishi", 'verbose_name_plural': "Ta'lim yo'nalishlari"},
        ),
    ]
