# Generated by Django 4.2.13 on 2024-05-30 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_applicant_applicationstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='additionalPhoneNumber',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
