# Generated by Django 4.2.13 on 2024-06-19 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_directionofeducation_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directionofeducation',
            name='examPassPercentage',
        ),
        migrations.AddField(
            model_name='applicant',
            name='birthDate',
            field=models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sanasi"),
        ),
        migrations.AddField(
            model_name='directionofeducation',
            name='active',
            field=models.BooleanField(default=True, verbose_name="Ta'lim yo'nalishi aktivligi"),
        ),
        migrations.AddField(
            model_name='typeofeducation',
            name='active',
            field=models.BooleanField(default=True, verbose_name="Ta'lim turi aktivligi"),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='applicationStatus',
            field=models.CharField(choices=[('DRAFT', 'QORALAMA'), ('SUBMITTED', 'ARIZA YUBORILDI'), ('REJECTED', 'ARIZA RAD ETILDI'), ('ACCEPTED', 'ARIZA QABUL QILINDI'), ('EXAMINED', 'IMTIHON TOPSHIRDI'), ('FAILED', 'IMTIHON MUVAFFAQIYATSIZ'), ('PASSED', "IMTHONDAN MUVAFFAQIYATLI O'TDI")], default='DRAFT', max_length=20, verbose_name='Arizachi holati'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='passport',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Pasport seriya va raqami'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='pinfl',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='Pinfl'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='updatedTime',
            field=models.DateTimeField(auto_now=True, verbose_name="Oxirgi o'zgarish sanasi"),
        ),
        migrations.AlterField(
            model_name='directionofeducation',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Qabul jadvalidagi ID'),
        ),
        migrations.AlterField(
            model_name='typeofeducation',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='Qabul jadvalidagi ID'),
        ),
    ]
