# Generated by Django 4.2.13 on 2024-06-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_directionofeducation_exampasspercentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='passport',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Pasport seriya va raqami'),
        ),
    ]
