# Generated by Django 4.2.13 on 2024-06-22 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_applicant_languageofeducation'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='birthCountry',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Tug'ilgan davlati"),
        ),
        migrations.AddField(
            model_name='applicant',
            name='birthPlace',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Tug'ilgan joyi"),
        ),
        migrations.AddField(
            model_name='applicant',
            name='citizenship',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Fuqaroligi'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'Erkak'), ('FEMALE', 'Ayol')], max_length=6, null=True, verbose_name='Jinsi'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='nationality',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Millati'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='photo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rasmi'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='directionOfEducation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants', to='users.directionofeducation', verbose_name="Ta'lim yo'nalishi"),
        ),
    ]
