# Generated by Django 4.2.13 on 2024-06-25 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_science_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='directionofeducation',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilganmi?"),
        ),
        migrations.AddField(
            model_name='typeofeducation',
            name='deleted',
            field=models.BooleanField(default=False, verbose_name="O'chirilganmi?"),
        ),
    ]
