# Generated by Django 4.2.13 on 2024-06-25 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_directionofeducation_deleted_typeofeducation_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='additionalPhoneNumber',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name="Qo'shimcha telefon raqami"),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='birthDate',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Tug'ilgan sanasi"),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='passport',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pasport seriya va raqami'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='phoneNumber',
            field=models.CharField(max_length=255, unique=True, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='pinfl',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Pinfl'),
        ),
    ]
