# Generated by Django 4.2.13 on 2024-07-02 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_applicant_additionalphonenumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='applicantId',
            field=models.IntegerField(blank=True, null=True, verbose_name='Arizachi ID'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='applicantNumber',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ariza raqami'),
        ),
    ]
