# Generated by Django 4.2.13 on 2024-07-04 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_applicant_applicantid_applicant_applicantnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='cityId',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tuman ID'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='cityName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tuman nomi'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='regionId',
            field=models.IntegerField(blank=True, null=True, verbose_name='Viloyat ID'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='regionName',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Viloyat nomi'),
        ),
    ]
