# Generated by Django 4.2.13 on 2024-07-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_applicant_cityid_applicant_cityname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='passportImageBack',
            field=models.ImageField(blank=True, null=True, upload_to='passport/images/back/', verbose_name='Pasport orqa rasmi'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='passportImageFront',
            field=models.ImageField(blank=True, null=True, upload_to='passport/images/front/', verbose_name='Pasport old rasmi'),
        ),
    ]
