# Generated by Django 4.2.13 on 2024-07-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_applicant_passportimageback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='passportImageBack',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pasport orqa rasmi'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='passportImageFront',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Pasport old rasmi'),
        ),
    ]
