# Generated by Django 4.2.13 on 2024-07-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_applicant_passportimageback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='passportImageBack',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='passport/images/back/', verbose_name='Pasport orqa rasmi'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='passportImageFront',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='passport/images/front/', verbose_name='Pasport old rasmi'),
        ),
    ]
