# Generated by Django 4.2.13 on 2024-07-23 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_applicant_passportimageback_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='dtmAbiturientNumber',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DTM abituriyent raqami'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='dtmScore',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='DTM natijasi'),
        ),
    ]
